author: "J3ang"
description: "I'm currently graduated from IIT with IT and Management degree where I have gained a broad range of knowledge and hands-on experiences in software development and the business side of project management. I fell in love with web development particularly. While I enjoy the client side development, I also enjoyed working with the back-end server side.
<br>
I worked on a couple of website projects besides the school work, where I  re-designed and developed the website from scratch for the client and provided the owner with an admin panel. And while I enjoyed working on these projects, I'd like the chance of working with others and learn more from each other, which is why I'm so excited and looking forward to joining a team as an intern to contribute and learn. "
keywords: "webdev"

email: "j3ang.info@gmail.com"
resume: "assets/j3ang_resume.pdf"

linkedin: "https://www.linkedin.com/in/j3ang/"
twitter: "https://twitter.com/j3ang_"
github: "https://github.com/j3ang"
instagram: "https://www.instagram.com/j3ang__/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

