# User config
author: "JW"
description: "Born in 1995. Neon | Guitar | Cat"
keywords: "1995, webdev"
email: "j3ang.info@gmail.com"
linkedin: "https://www.linkedin.com/in/j3ang/"
twitter: "https://twitter.com/j3ang_"
github: "https://github.com/jwang206"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
