author: "J3ang"
description: "Neon • Guitar • Cat's Dad"
keywords: "webdev"

email: "j3ang.info@gmail.com"
resume: "assets/j3ang_resume.pdf"

linkedin: "https://www.linkedin.com/in/j3ang/"
twitter: "https://twitter.com/j3ang_"
github: "https://github.com/j3ang"
instagram: "https://www.instagram.com/j3ang__/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

